import { anthropic, CLAUDE_MODEL } from "./anthropic";
import { generateWithLocalAI, type LocalAIConn } from "./localAI";
import type { Difficulty, QuestionKind } from "./types";

export interface StudyPack {
  summary: {
    overview: string;
    key_points: string[];
    key_terms: { term: string; definition: string }[];
  };
  quiz: {
    title: string;
    questions: {
      kind: QuestionKind;
      prompt: string;
      options?: string[];
      answer: string;
      explanation?: string;
    }[];
  };
}

const STUDY_PACK_TOOL = {
  name: "emit_study_pack",
  description:
    "Return a structured study pack (summary + quiz) for the provided source text.",
  input_schema: {
    type: "object" as const,
    properties: {
      summary: {
        type: "object",
        properties: {
          overview: {
            type: "string",
            description: "2-4 sentence plain-language overview of the material.",
          },
          key_points: {
            type: "array",
            items: { type: "string" },
            description: "5-8 concise bullet takeaways.",
          },
          key_terms: {
            type: "array",
            items: {
              type: "object",
              properties: {
                term: { type: "string" },
                definition: { type: "string" },
              },
              required: ["term", "definition"],
            },
            description: "Important terms with short definitions.",
          },
        },
        required: ["overview", "key_points", "key_terms"],
      },
      quiz: {
        type: "object",
        properties: {
          title: { type: "string" },
          questions: {
            type: "array",
            items: {
              type: "object",
              properties: {
                kind: { type: "string", enum: ["mcq", "tf", "short"] },
                prompt: { type: "string" },
                options: {
                  type: "array",
                  items: { type: "string" },
                  description:
                    "For mcq: 4 options. For tf: ['True','False']. Omit for short.",
                },
                answer: {
                  type: "string",
                  description:
                    "The exact correct option text (mcq/tf) or a concise model answer (short).",
                },
                explanation: { type: "string" },
              },
              required: ["kind", "prompt", "answer", "explanation"],
            },
          },
        },
        required: ["title", "questions"],
      },
    },
    required: ["summary", "quiz"],
  },
};

export interface GenerateOptions {
  text: string;
  title: string;
  difficulty: Difficulty;
  numQuestions: number;
  kinds: QuestionKind[];
}

// Keep well under the model context window; trim very large documents.
const MAX_CHARS = 60_000;

// Self-hosted model (Ollama / any OpenAI-compatible server) for the "AI" path.
// When OLLAMA_URL is set, every user's quiz + summary is generated by this model
// server-to-server (no per-user connection, no CORS). Falls back to Claude when
// unset, so the app still works without it.
function hostedModelConn(): LocalAIConn | null {
  const base = process.env.OLLAMA_URL?.trim();
  if (!base) return null;
  return {
    base_url: base,
    model: process.env.OLLAMA_MODEL?.trim() || "gemma3",
    api_key: process.env.OLLAMA_API_KEY?.trim() || null,
  };
}

// Bound how long a slow self-hosted model may run (stays under the route's
// maxDuration so we return a clean error rather than being killed mid-flight).
const HOSTED_MODEL_TIMEOUT_MS = 110_000;

export async function generateStudyPack(
  opts: GenerateOptions,
): Promise<StudyPack> {
  const { text, title, difficulty, numQuestions, kinds } = opts;

  // Prefer the self-hosted model (e.g. Gemma via Ollama) when configured.
  const conn = hostedModelConn();
  if (conn) {
    return generateWithLocalAI({
      conn,
      text,
      title,
      difficulty,
      numQuestions,
      kinds,
      signal: AbortSignal.timeout(HOSTED_MODEL_TIMEOUT_MS),
    });
  }

  const source = text.slice(0, MAX_CHARS);

  const kindLabel = kinds
    .map((k) => (k === "mcq" ? "multiple-choice" : k === "tf" ? "true/false" : "short-answer"))
    .join(", ");

  const message = await anthropic.messages.create({
    model: CLAUDE_MODEL,
    max_tokens: 4096,
    tools: [STUDY_PACK_TOOL],
    tool_choice: { type: "tool", name: "emit_study_pack" },
    messages: [
      {
        role: "user",
        content: `You are an expert study assistant. From the source material below, produce:
1. A clear summary (overview, key points, key terms).
2. A ${numQuestions}-question quiz at ${difficulty} difficulty using these question types: ${kindLabel}.

Rules:
- Base everything strictly on the source; do not invent facts.
- For multiple-choice, give exactly 4 plausible options and set "answer" to the exact correct option text.
- For true/false, options must be ["True","False"].
- Always include a one-sentence explanation for each question.
- Quiz title should reference the material "${title}".

Source material:
"""
${source}
"""`,
      },
    ],
  });

  const toolUse = message.content.find((b) => b.type === "tool_use");
  if (!toolUse || toolUse.type !== "tool_use") {
    throw new Error("Model did not return a study pack.");
  }
  return toolUse.input as StudyPack;
}
